### ISSUE TITLE
Add repository-information to repology

### ISSUE THREAD

**Issue by rndmh3ro** [upciti/wakemeops#1048]
### Is your feature request related to a problem? Please describe

> Repology monitors a huge number of [package](https://en.wikipedia.org/wiki/Package_(package_management_system)) [repositories](https://en.wikipedia.org/wiki/Software_repository) and other [sources](https://repology.org/#repos-footnote) comparing packages versions across them and gathering other information. Repology shows you in which repositories a given project is packaged, which version is the latest and which needs updating, who maintains the package, and other related information. Repology might be useful
- https://repology.org/

I'd like to see the wakemeops-repository to repology added, so I can use repology as a source when checking out which versions are available. In particular I want to use it as a [datasource](https://docs.renovatebot.com/modules/datasource/repology/) in renovate, so the versions can be automatically updated.

To get the repository added to repology, one has to create a issue (or pull request) with the following infomation:

```
**Repository data location(s)**
<!--
Link(s) to machine readable package data (may express multiple links in free form).
-->

- https://mymegarepo.org/22.04/{main,contrib,non-free}/packages.json

**Package links**
<!--
Examples or free form templates of links for individual packages. Link to package recipe is mandatory.
Other useful link types include package page, package related issues, build status or logs.
-->

- **Recipe**: https://github.com/mymygarepo/packages/blob/master/{pkgname}/recipe.json
- Package page: https://mymegarepo.org/packages/{pkgname}/
- Package sources: https://github.com/mymygarepo/packages/tree/master/{pkgname}/
- Issues: https://bugzilla.mymegarepo.org/buglist.cgi?quicksearch={pkgname}
- Build status: https://builder.mymegarepo.org/{pkgname}/status
- Build log: https://builder.mymegarepo.org/{pkgname}/buildlogs/latest

**Additional details**
<!--
- More links, such as distribution/repository homepage or GitHub organization
- Brand color, if any
- EoL date, if applicable
- Contact in case of fetch failures or data problems
- Details on custom data format, if it makes sense
- Any other details
-->
```

See here: https://github.com/repology/repology-updater/issues/new?assignees=&labels=new+source&template=newrepo.md

I don't feel comfortable about all the details and links to create an issue with repology so I hope that you can provide the information so I can create an issue (or you directly create the issue).

Thanks!

### Describe the proposed solution

Add the repository-infos to repology by creating a issue: https://github.com/repology/repology-updater/issues/new?assignees=&labels=new+source&template=newrepo.md

**Comment by fyhertz** [comment]
That's a great idea, I will look into it!

**Comment by fyhertz** [comment]
https://github.com/repology/repology-updater/issues/1316

**Comment by fyhertz** [comment]
I've opened an issue on repology here: https://github.com/repology/repology-updater/issues/1316

**Comment by fyhertz** [comment]
See https://github.com/repology/repology-updater/commit/0665ee77fe072b6c5f6a602974aaba59c9a5fd3b.
