### ISSUE TITLE
Podman

### ISSUE THREAD

**Issue by rndmh3ro** [upciti/wakemeops#1130]
### Package Name

Podman is already in the upstream-repositories of Debian and Ubuntu, however with a rather old version.

Since podman is also distributed via Github Releases, would you be willing to accept a PR to add podman to the repository, so we get the latest version?

### Package Description

 Podman: A tool for managing OCI containers and pods. 

### Project URL

github.com/containers/podman/

**Comment by fyhertz** [comment]
Hello,

Why not, last time we checked it seemed complicated though, maybe that was before they published a static release.

Have to tried to install it from the release page and do you know which dependencies we need to make it fully functionnal?

**Comment by rndmh3ro** [comment]
It seems that it's not as easy as just downloading the binary and running it, see: https://podman.io/getting-started/installation.html

So I'm not really sure if this is a useful addition since there are many different ways to install a current podman.

**Comment by fyhertz** [comment]
Indeed.

Lets close the issue for now, it would be nice to have podman in the project but we would need to carefully check that all features work properly on supported distributions.
