### ISSUE TITLE
Support for Delta

### ISSUE THREAD

**Issue by rndmh3ro** [upciti/wakemeops#389]
### Package Name

delta

### Package Component

terminal

### Package Description

 A syntax-highlighting pager for git, diff, and grep output 

Installation: https://dandavison.github.io/delta/installation.html

### Project URL

https://github.com/dandavison/delta

**Comment by benjamin-texier** [comment]
Hi @rndmh3ro
Thanks for your contribution.
The package will be available in a few minutes

**Comment by benjamin-texier** [comment]
Done: you can download it with:

* apt install git-delta

Thanks for your contribution

**Comment by rndmh3ro** [comment]
Thanks for this ultra fast implementation!
