### ISSUE TITLE
Badges aren't updating with latest version releases

### ISSUE THREAD

**Issue by gabrie30** [upciti/wakemeops#642]
### Describe the Bug

For repo https://github.com/gabrie30/ghorg

The github badge below shows an out of date version.

![image](https://user-images.githubusercontent.com/1512282/183539494-3df25640-8042-44cb-b402-18316c352806.png)

The [latest release](https://github.com/gabrie30/ghorg/releases/tag/v1.8.3) is 1.8.3

### Steps to Reproduce

See description

### Expected Behaviour

See description

### Actual Behaviour

See description

### Environment

```shell
See description
```

**Comment by benjamin-texier** [comment]
Hi @gabrie30,

Indeed, we currently have a problem with the update of the documentation.
We are sorry for the inconvenience caused.

We will patch this later today,

**Comment by benjamin-texier** [comment]
We have just patched the documentation pipeline.
Normally, everything should be fine now.

Thanks for the feedback and for using our badge
